" Small, plugin-free Vim config for servers.

set nocompatible
filetype plugin indent on
syntax enable

set number
set relativenumber
set ignorecase
set smartcase
set splitright
set splitbelow
set cursorline
set scrolloff=8
set nowrap
set confirm
set hidden
set mouse=a
set backspace=indent,eol,start
set wildmenu
set wildignorecase
set list
set listchars=tab:>\ ,trail:.,nbsp:_

set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4

if has('persistent_undo')
  silent! call mkdir(expand('~/.vim/undo'), 'p')
  set undofile
  set undodir=~/.vim/undo//
endif

if has('clipboard')
  set clipboard=unnamedplus
endif

if has('termguicolors')
  set termguicolors
endif

let mapleader = ' '
nnoremap <Esc> :nohlsearch<CR>
nnoremap <leader>pv :Explore<CR>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap n nzzzv
nnoremap N Nzzzv
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
nnoremap <leader>d "_d
vnoremap <leader>d "_d
nnoremap <leader>bn :bnext<CR>
nnoremap <leader>bp :bprevious<CR>
nnoremap <leader>bc :bdelete<CR>

if has('clipboard')
  nnoremap <leader>y "+y
  vnoremap <leader>y "+y
  nnoremap <leader>p "+p
  vnoremap <leader>p "+p
endif

augroup dotfiles
  autocmd!
  autocmd FileType json,jsonc,sh,bash,zsh,yaml setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2
  autocmd FileType make setlocal noexpandtab
  autocmd FileType gitcommit setlocal spell textwidth=72
  autocmd FileType markdown,text setlocal spell textwidth=70
augroup END
