date: +%m/%d/%y %k:%M
hyperlink: never
no-symlink: false
permission: octal
sorting:
  dir-grouping: none
icons:
  when: never
literal: true
blocks:
  - permission
  - user
  - size
  - date
  - git
  - name
