blocks:
  - permission
  - user
  - group
  - size
  - date
  - name
color:
  theme: custom
date: +%m/%d/%y %k:%M
hyperlink: never
size: default
no-symlink: false
permission: octal
sorting:
  dir-grouping: none
icons:
  when: never
literal: true
truncate-owner:
  after: 10
  marker: …