# Config for interactive shells, from "diy++" in romkatv/zsh-bench

# Instant Prompt -----------------------------------------------------

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Environment --------------------------------------------------------

# Paths --------------------------------------------------------------

typeset -gU fpath FPATH

fpath=($HOME/.zfunc $fpath)

if [[ -d /opt/homebrew/share/zsh/site-functions ]]; then
  fpath[2,1]=(/opt/homebrew/share/zsh/site-functions)
fi

# Options ------------------------------------------------------------

setopt AUTO_CD
setopt ALWAYS_TO_END    # Move cursor to end after completion
setopt APPEND_HISTORY   # Append rather than overwrite history file
setopt COMPLETE_IN_WORD # Allow completion in middle of words
setopt CORRECT          # Command correction suggestions
setopt NO_BEEP
setopt NO_CASE_GLOB
setopt NO_CLOBBER

setopt EXTENDED_HISTORY        # Save timestamp and duration
setopt HIST_EXPIRE_DUPS_FIRST  # Expire duplicates first when trimming history
setopt HIST_FCNTL_LOCK         # Lock history file when possible
setopt HIST_IGNORE_ALL_DUPS    # Remove older duplicate when new one added
setopt HIST_IGNORE_SPACE       # Don't save commands starting with space
setopt HIST_REDUCE_BLANKS      # Remove extra whitespace before saving
setopt HIST_SAVE_NO_DUPS       # Don't write duplicate commands
setopt HIST_VERIFY             # Show expanded history command before executing
setopt INC_APPEND_HISTORY_TIME # Write commands immediately w/timestamps
setopt SHARE_HISTORY           # Share history between all zsh sessions

# Functions ----------------------------------------------------------

source "$DOTFILES_DIR/shell/common/functions.sh"

function zcompile-files() {
  local f zwc
  for f; do
    zwc="${f}.zwc"
    if [[ ! -e "$zwc" || "$f" -nt "$zwc" ]]; then
      zcompile -R -- "$zwc" "$f"
    fi
  done
}

# Powerlevel10k ------------------------------------------------------

if [[ -n $ZSH_VERSION ]]; then
  ZSH_DIR="$DOTFILES_DIR/shell/zsh"
  P10K_DIR="${XDG_DATA_HOME}/powerlevel10k"
  
  if [[ -d $P10K_DIR ]]; then
    source "$P10K_DIR/powerlevel10k.zsh-theme"
    [[ -r $HOME/.p10k.zsh ]] && source "$HOME/.p10k.zsh"
    [[ -r $ZSH_DIR/p10k.zsh && ! -r ~/.p10k.zsh ]] && source "$ZSH_DIR/p10k.zsh"
  fi

  unset P10K_DIR ZSH_DIR
fi

# Completion ---------------------------------------------------------

source "$DOTFILES_DIR/shell/common/completions.sh"

ZSH_AUTOSUGGEST_MANUAL_REBIND=1

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}' # No case
zstyle ':completion:*' menu select                     # Menu
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "$HOME"/.zsh/cache

autoload -Uz compinit

zcompdump=${ZDOTDIR:-$HOME}/.zcompdump
if [[ $zcompdump(#qN.mh+24) ]]; then
  compinit -d "$zcompdump"
else
  compinit -C -d "$zcompdump"
fi

zcompile-files "$zcompdump"
unset zcompdump

# Aliases ------------------------------------------------------------

source "$DOTFILES_DIR/shell/common/aliases.sh"

# Keybindings --------------------------------------------------------

bindkey -e

bindkey '^[[1;3D' backward-word
bindkey '^[[1;3C' forward-word
bindkey '^[[1;9D' beginning-of-line
bindkey '^[[1;9C' end-of-line
bindkey '^[[3;3~' backward-kill-word
bindkey '^[[3;9~' kill-word

autoload -Uz up-line-or-beginning-search down-line-or-beginning-search

zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search

WORDCHARS=${WORDCHARS//\//}

# Tools --------------------------------------------------------------

source "$DOTFILES_DIR/shell/common/tools.sh"

# Cleanup ------------------------------------------------------------

unfunction zcompile-files
