
# General options ------------------------------------------

shopt -s cdspell cmdhist histappend

# https://github.com/mathiasbynens/dotfiles/blob/main/.bash_profile
for option in autocd checkjobs globstar; do
	shopt -s "$option" 2> /dev/null;
done;


# Include .bashrc ------------------------------------------

[ -f ~/.bashrc ] && . ~/.bashrc
